# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0182c22519d85d8555f81b19472023e743fa71636794427324a964376ef90ca4a9fc40c0f0f016edaf868e14e66bda7f927a0d7d89b8913a562b03d034aad756

test:
  secret_key_base: 46b5a5d4e705ffba9bb0429a272fc2186aa535040e340bedab6dd7e8e93d8b6dd8e17f6b3c9d08084148469c043afe6433b12894b77e497bd15f78e2d61b7961

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
